# This is a basic workflow to help you get started with Actions

name: SBOM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildAndUpload:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
         distribution: 'temurin'
         java-version: 17
         architecture: x64
    - name: Build with Maven
      run: mvn -B package -DskipTests=true
    - name: Path Call Out
      run: ls -la . ./target/* 
    - uses: anchore/sbom-action@v0
      with:
        image: ./target/webgoat-8.2.3-SNAPSHOT.jar
        dependency-snapshot: true
 

